import "./globals.css";
import Navigation from "@/components/Navigation";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { Open_Sans, Roboto_Mono } from "next/font/google";

const open_sans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${open_sans.variable} ${roboto_mono.variable}`}>
      <body>
        <Header />
        <Navigation />

        {children}
        <Footer />
      </body>
    </html>
  );
}
